name: e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jawnClient:
    name: Jawn Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make sure types were generated
        working-directory: valhalla/jawn
        run: |
          npm install
          bash tsoa_run.sh
          python3 genTypes.py

          if git status | grep -e "jawnTypes" -e "swagger"; then
              echo "Please run the type generation script to update the types."
              git diff
              exit 1
          fi

  costs:
    name: Cost Calculation Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run node tests
        working-directory: costs
        run: |
          npm install
          npm run test

      - name: Ensure copy was ran
        working-directory: costs
        run: |
          # Make sure the content of /src is copied to ../worker/src/packages/cost and ../web/packages/cost before pushing
          # we can do this by calculating size of the content of /src and then copying it to the respective folders
          # Compute the size of the content of /src
          DIR1=../worker/src/packages/cost
          DIR2=./src

          # Generate hash lists
          find $DIR1 -type f -print0 | sort -z | xargs -0 sha256sum | awk '{print $1}' > /tmp/dir1_hashes_only.txt
          find $DIR2 -type f -print0 | sort -z | xargs -0 sha256sum | awk '{print $1}' > /tmp/dir2_hashes_only.txt

          # Compare the hash lists
          if cmp -s /tmp/dir1_hashes_only.txt /tmp/dir2_hashes_only.txt; then
              echo "Directories have the same contents."
          else
              echo "Directories have different contents."
              echo "Please run the copy script to update the contents of the directories."
              exit 1
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint worker
        run: |
          cd worker
          yarn install
          yarn lint
